# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ef28736a9dfd996a9d8c174365969dcdc9b714528d3ad4d361dd5efa6fb66d6b98850c752e1f9331972be3cb414282e9a8d11381588a2ae0045b66322d6c0d5a

test:
  secret_key_base: ebf041712c71c9626174c450a7516c8533da72ecfb1d1b176c5e72c21b1821da33641208dc7c066e3c16eabf3ee28484d04c57d30eae499a868a79bd77000044

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
